src/main/java/cn/gcu/entity/ApplyEntity.java
package cn.gcu.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

@Entity
@Table(name = "tb_apply")
public class ApplyEntity extends IdEntity {

	private static final long serialVersionUID = 6590214666786068128L;
	@ManyToOne
	@JoinColumn(name = "f_job")
	private JobsEntity job;
	@JsonIgnore
	@OneToOne
	@JoinColumn(name = "f_user")
	private UserEntity user;
	@JsonIgnore
	@OneToOne
	@JoinColumn(name = "f_resume")
	private ResumeEntity resume;
	@Column(name = "f_apply_time")
	private Date applyTime;
	@Column(name = "f_is_offer")
	private boolean isOffer = false;
	@Column(name = "f_is_handle")
	private boolean isHandle = false;

	public JobsEntity getJob() {
		return job;
	}

	public void setJob(JobsEntity job) {
		this.job = job;
	}

	public UserEntity getUser() {
		return user;
	}

	public void setUser(UserEntity user) {
		this.user = user;
	}

	public ResumeEntity getResume() {
		return resume;
	}

	public void setResume(ResumeEntity resume) {
		this.resume = resume;
	}

	public Date getApplyTime() {
		return applyTime;
	}

	public void setApplyTime(Date applyTime) {
		this.applyTime = applyTime;
	}

	public boolean isOffer() {
		return isOffer;
	}

	public void setOffer(boolean isOffer) {
		this.isOffer = isOffer;
	}

	public boolean isHandle() {
		return isHandle;
	}

	public void setHandle(boolean isHandle) {
		this.isHandle = isHandle;
	}

}

src/main/java/cn/gcu/controller/EnterpiseController.java
package cn.gcu.controller;

import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import cn.gcu.entity.ApplyEntity;
import cn.gcu.entity.EnterpiseEntity;
import cn.gcu.entity.JobsEntity;
import cn.gcu.pojo.Page;
import cn.gcu.service.ApplyService;
import cn.gcu.service.JobService;
import cn.gcu.utils.PageUtil;

@Controller
public class EnterpiseController {
	
	@Resource
	JobService jobService;
	@Resource
	ApplyService applyService;
	
	@RequestMapping(value="enterprise-login.html")
	public String getEnterpiseLoginPage() {
		return "enterpise/login";
	}
	
	@RequestMapping(value="mgr-apply.html")
	public String getEnterpiseLoginPage(String page,HttpServletRequest request,HttpServletResponse response ) throws IOException {
		String type = (String) request.getSession().getAttribute("type");
		if(type!=null && type.equals("enterpise")) {
			int currentPage = 1;
			if(page!=null && !page.isEmpty()) {
				try {
					currentPage = Integer.valueOf(page);
				}catch(Exception e) {
					
				}
			}
			EnterpiseEntity enterpise = (EnterpiseEntity) request.getSession().getAttribute("enterpiseEntity");
			Page<ApplyEntity> applyPage = applyService.getApplyByEnterpise(enterpise, currentPage);
			request.setAttribute("applyPage", applyPage);
			request.setAttribute("navi", PageUtil.generateBootstrapNav(applyPage, "mgr-apply.html?page=${pageNumber}"));
		}else {
			response.sendRedirect("index.html");
		}
		return "enterpise/mgr-apply";
	}
	
	@RequestMapping(value="mgr-jobs.html")
	public String getEnterpiseJobsPage(String page,HttpServletRequest request,HttpServletResponse response ) throws IOException {
		String type = (String) request.getSession().getAttribute("type");
		if(type!=null && type.equals("enterpise")) {
			int currentPage = 1;
			if(page!=null && !page.isEmpty()) {
				try {
					currentPage = Integer.valueOf(page);
				}catch(Exception e) {
					
				}
			}
			EnterpiseEntity enterpise = (EnterpiseEntity) request.getSession().getAttribute("enterpiseEntity");
			Page<JobsEntity> jobsPage = jobService.getJobsByEnterpise(enterpise, currentPage);
			request.setAttribute("jobsPage", jobsPage);
			request.setAttribute("navi", PageUtil.generateBootstrapNav(jobsPage, "mgr-jobs.html?page=${pageNumber}"));
		}else {
			response.sendRedirect("index.html");
		}
		return "enterpise/mgr-jobs";
	}
	
	@RequestMapping(value="publish-jobs.html")
	public String getPublishJobsPage(HttpServletRequest request,HttpServletResponse response ) throws IOException {
		String type = (String) request.getSession().getAttribute("type");
		if(type==null || !type.equals("enterpise")) {
			response.sendRedirect("index.html");
		}
		return "enterpise/publish-jobs";
	}
	
	@RequestMapping(value="view-apply.html")
	public String viewApply( String id, HttpServletRequest request,HttpServletResponse response ) throws IOException {
		String type = (String) request.getSession().getAttribute("type");
		if(type==null || !type.equals("enterpise")) {
			response.sendRedirect("index.html");
		}
		if(id!=null && id.length() > 0){
			ApplyEntity apply = applyService.getApplyById(id);
			if(apply!=null) {
				request.setAttribute("applyEntity", apply);
			}else {
				response.sendRedirect("mgr-apply.html");
			}
		}else {
			response.sendRedirect("mgr-apply.html");
		}
		
		return "enterpise/view-apply";
	}
	
	@RequestMapping(value="enterpise/handle_apply")
	@ResponseBody
	public Map<String,Object> handleApply( String id, String flag,HttpServletRequest request,HttpServletResponse response ) throws IOException {
		Map<String,Object> res  = new HashMap<String,Object>();
		String type = (String) request.getSession().getAttribute("type");
		EnterpiseEntity enterpise = (EnterpiseEntity) request.getSession().getAttribute("enterpiseEntity");
		if(type==null || !type.equals("enterpise")) {
			response.sendRedirect("index.html");
		}
		if(id!=null && id.length() > 0){
			ApplyEntity apply = applyService.getApplyById(id);
			if(apply!=null) {
				if(enterpise.getId().equals(apply.getJob().getEnterpise().getId())) {
					apply.setHandle(true);
					if(flag!=null && flag.equals("accept")) {
						apply.setOffer(true);
					}else {
						apply.setOffer(false);
					}
					applyService.updateApply(apply);
					res.put("status", "ok");
				}else {
					res.put("status", "error");
				}
			}else {
				res.put("status", "error");
			}
		}else {
			res.put("status", "error");
		}
		
		return res;
	}

}

src/main/java/cn/gcu/controller/LoginController.java
package cn.gcu.controller;

import java.util.Date;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import cn.gcu.entity.EnterpiseEntity;
import cn.gcu.entity.UserEntity;
import cn.gcu.entity.VericodeEntity;
import cn.gcu.service.EnterpiseService;
import cn.gcu.service.UserService;
import cn.gcu.service.VericodeService;
import cn.gcu.utils.SecurityUtil;
import cn.gcu.utils.VericodeUtil;

@Controller
public class LoginController {
	
	@Resource
	UserService userService;
	
	@Resource
	EnterpiseService enterpiseService;
	
	@Resource
	VericodeService vericodeService;
	
	/**
	 * 同步请求，返回JSP
	 * @param request
	 * @param response
	 * @return
	 */
	@RequestMapping(value="login.html")
	public String getLoginPage(HttpServletRequest request,HttpServletResponse response) {
		return "public/default-login";
	}
	
	@RequestMapping(value="regisiter.html")
	public String getRegisiterPage(HttpServletRequest request,HttpServletResponse response) {
		return "public/regisiter";
	}
	
	@RequestMapping(value="forget-password.html")
	public String getForgetPasswordPage(HttpServletRequest request,HttpServletResponse response) {
		return "public/forget-password";
	}
	
	/**
	 * 异步请求返回JSON串
	 * @param request
	 * @param response
	 * @return
	 */
	@RequestMapping(value="public/login_comfirm")
	@ResponseBody
	public Map<String,Object> doLoginComfirm(String username, String password ,HttpServletRequest request,HttpServletResponse response) {
		Map<String,Object> res = new HashMap<String,Object>();
		if(!username.isEmpty() && ! password.isEmpty()) {
			UserEntity userEntity = userService.getUserByUserName(username);
			if( userEntity!=null ) {
				String encryptPassword = SecurityUtil.encryptPassword(password);
				if(encryptPassword.equals(userEntity.getPassword())) {
					res.put("status", "ok");
					res.put("nextStep", "index.html");
					request.getSession().setAttribute("isLogin", true);
					request.getSession().setAttribute("type", "user");
					request.getSession().setAttribute("userEntity", userEntity);
				}else {
					res.put("status", "error");
					res.put("message", "账户或密码有误");
				}
			}else {
				res.put("status", "error");
				res.put("message", "账户或密码有误");
			}
		}else {
			res.put("status", "error");
			res.put("message", "请求有误");
		}
		return res;
	}
	
	@RequestMapping(value="user_register")
	@ResponseBody
	public Map<String ,Object>userRegister(HttpServletRequest request,HttpServletResponse response){
		System.out.println("start register");
		Map<String ,Object> res = new HashMap<String ,Object>();
		String username = request.getParameter("username");
		String password = request.getParameter("password");
		String phone = request.getParameter("phone");
		String code = request.getParameter("vericode");
		System.out.println("start register");
		if(!username.isEmpty()&&!password.isEmpty()&&!phone.isEmpty()) {
			UserEntity user = userService.getUserByUserName(username);
				if(user!=null) {
					res.put("status", "error");
					res.put("message", "该用户已注册");
					return res;
				}
			VericodeEntity vericode = vericodeService.getVericodeByPhone(phone);
			if(vericode!=null) {
				if(vericode.getCode().equals(code)) {
					user = new UserEntity();
					user.setMobilePhone(phone);
					user.setPassword(SecurityUtil.encryptPassword(password));
					user.setUserName(username);
					userService.addUser(user);
					res.put("status", "ok");
					res.put("nextStep", "index.html");
					request.getSession().setAttribute("isLogin", true);
					request.getSession().setAttribute("type", "user");
					request.getSession().setAttribute("userEntity", user);
				
				}
				else {
					res.put("status", "error");
					res.put("message", "验证码错误");
				}
			}
			else {
				res.put("status", "error");
				res.put("message", "验证码过期");
			}
		}
		else {
			res.put("status", "error");
			res.put("message","请求有误");
		}
		return res;
	}
	
	@RequestMapping(value="enterpise_login_confirm")
	@ResponseBody
	public Map<String ,Object> enterpiseLogin(HttpServletRequest request,HttpServletResponse response){
		Map<String ,Object> res = new HashMap<String ,Object>();
		String username = request.getParameter("username");
		String password = request.getParameter("password");
		if(!username.isEmpty()&&!password.isEmpty()) {
			EnterpiseEntity enterpise = enterpiseService.getEnterpiseByUserName(username);
			if(enterpise!=null) {
				String enterpisePassword = SecurityUtil.encryptPassword(password);
				if(enterpisePassword.equals(enterpise.getPassword())) {
					res.put("status", "ok");
					res.put("nextStep", "index.html");
					request.getSession().setAttribute("isLogin", true);
					request.getSession().setAttribute("type", "enterpise");
					request.getSession().setAttribute("enterpiseEntity", enterpise);
				}
				else {
					res.put("status", "error");
					res.put("message", "账户或密码有误");
				}
			}
			else {
				res.put("status", "error");
				res.put("message", "账号或密码有误");
			}
		}
		else {
			res.put("status", "error");
			res.put("message", "请求有误");
		}
		return res;
	}
	
	@RequestMapping(value="enterpise_register")
	@ResponseBody
	public Map<String ,Object> enterpiseRegister(HttpServletRequest request,HttpServletResponse response){
		Map<String ,Object> res = new HashMap<String ,Object>();
		String username = request.getParameter("username");
		String password = request.getParameter("password");
		String enterpiseName = request.getParameter("enterpiseName");
		EnterpiseEntity enterpise = enterpiseService.getEnterpiseByUserName(username);
		if(!username.isEmpty()&&!password.isEmpty()&&!enterpiseName.isEmpty()) {
			if(enterpise==null) {
				enterpise = enterpiseService.getEnterpiseByEnterpiseName(enterpiseName);
				if(enterpise==null) {
					enterpise = new EnterpiseEntity();
					enterpise.setEnterpiseName(enterpiseName);
					enterpise.setPassword(SecurityUtil.encryptPassword(password));
					enterpise.setUserName(username);
					enterpiseService.addEnterpise(enterpise);
					res.put("status", "ok");
					res.put("nextStep","index.html");
					request.getSession().setAttribute("isLogin", true);
					request.getSession().setAttribute("type", "enterpise");
					request.getSession().setAttribute("enterpiseEntity", enterpise);
				}
				else {
					res.put("status", "error");
					res.put("message", "公司名称已注册");
				}
			}
			else {
				res.put("status", "error");
				res.put("message","账号已注册");
			}
		}
		return res;
	}
	
	@RequestMapping(value="getVericode")
	@ResponseBody
	public Map<String ,Object> getVericode(HttpServletRequest request,HttpServletResponse response){
		System.out.println("getVericode");
		Map<String ,Object> res = new HashMap<String ,Object>();
		Date getVericodeDate = (Date)request.getSession().getAttribute("getVericodeDate");
		String phone = request.getParameter("phone");
		if(getVericodeDate==null || getVericodeDate.compareTo(new Date())<0) {
			String verificationCode = VericodeUtil.sendVerificationCode();
			Date generateDate = new Date();
			Date expireDate = new Date(generateDate.getTime()+60000);
			request.getSession().setAttribute("getVericodeDate", expireDate);
			VericodeEntity vericode = new VericodeEntity();
			vericode.setCode(verificationCode);
			vericode.setGenerateDate(generateDate);
			vericode.setExpireDate(expireDate);
			vericode.setPhone(phone);
			vericodeService.addVericode(vericode);
			res.put("status", "ok");
		}
		else {
			res.put("status", "error");
			res.put("message", "请求过于频繁，请稍后再试");
		}
		return res;
	}
	
	@RequestMapping(value="forget_password")
	@ResponseBody
	public Map<String ,Object> forgetPassword(HttpServletRequest request,HttpServletResponse response){
		Map<String ,Object> res = new HashMap<String ,Object>();
		String username = request.getParameter("username");
		String code = request.getParameter("code");
		String newPassword = request.getParameter("newPassword");
		String phone = request.getParameter("phone");
		VericodeEntity vericode = vericodeService.getVericodeByPhone(phone);
		if(vericode!=null) {
			if(vericode.getCode().equals(code)) {
				UserEntity user = userService.getUserByUserName(username);
				user.setPassword(SecurityUtil.encryptPassword(newPassword));
				userService.updateUser(user);
				res.put("status", "ok");
				request.getSession().setAttribute("isLogin", true);
				request.getSession().setAttribute("type", "user");
				request.getSession().setAttribute("userEntity", user);
			}
			else {
				res.put("status", "error");
				res.put("message", "验证码错误");
			}
		}
		else {
			res.put("status", "error");
			res.put("message", "验证码过期");
		}
		return res;
	}
		
	@RequestMapping(value="logout")
	public void logout(HttpServletRequest request , HttpServletResponse response) throws IOException {
		request.getSession().invalidate();
		response.sendRedirect("index.html");
	}
}

src/main/webapp/WEB-INF/jsp/enterpise/mgr-apply.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
 <%@ taglib prefix="c"   uri="http://java.sun.com/jsp/jstl/core" %>
 
<!DOCTYPE HTML>
<html lang="zh-CN">

<head>
    <meta charset="UTF-8">
    <title>万才网</title>
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="apple-mobile-web-app-capable" content="no" />
    <meta name="format-detection" content="telephone=no">
    <link rel="stylesheet" type="text/css" href="${pageContext.request.contextPath}/res/css/style-bootstrap.css" />
    <link rel="stylesheet" type="text/css" href="${pageContext.request.contextPath}/res/css/style-enterpise.css" />
</head>

<body>
    <!-- Navbar Begin -->
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
                    aria-expanded="false">
                    <span class="sr-only">展开导航栏</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">万才网</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="index.html">首页</a>
                    </li>
                    <li class="active">
                        <a href="index.html">招聘管理</a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="logout">退出</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- Navbar end -->
    <!-- Banner Begin -->
    <div class="banner-container">
        <p class="title">招聘管理后台</p>
        <p>HR Control Panel</p>
    </div>
    <!-- Banner End -->
    <!-- Main Container -->
    <div class="container content">
        <div class="col-md-3">
            <div class="list-group">
                <div class="list-group-item header"> 菜单 Menu</div>
                <a href="mgr-jobs.html" class="list-group-item">招聘职位管理</a>
                <a href="mgr-apply.html" class="list-group-item">简历投递管理</a>
            </div>
        </div>
        <div class="col-md-9">
            <div class="list-group row">
                <div class="list-group-item text-left header">目前收到的简历</div>
                <!-- Item Begin -->
                <c:forEach items="${requestScope.applyPage.pageData}" var="item">
                 <a href="view-apply.html?id=${item.id }" class="list-group-item text-left">
                    <div class="row">
                        <div class="col-md-8 col-xs-8 col-sm-8">
                            <p class="job">${item.job.jobName }</p>
                            <p>${item.resume.name }</p>
                        </div>
                        <div>
                        <c:if test="${item.handle }">
                        		<c:if test="${item.offer }">
                        		 <p class="status offer">企业批准</p>
                        		</c:if>
                        		<c:if test="${!item.offer }">
                        		 <p class="status refuse">企业已回绝</p>
                        		</c:if>
                        </c:if>
                        <c:if test="${!item.handle }">
                        <p class="status not-handle">企业未处理</p>
                        </c:if>
                            
                        </div>
                    </div>
                </a>
                </c:forEach>


            </div>
            <!-- Pagination Begin -->
            ${navi }
            <!-- Pagination End -->
        </div>
    </div>
    <div class="footer">
        <p>
            <a href="enterprise-login.html">我要发布招聘信息</a>
        </p>
        <p>Guangzhou College &copy; 2006-2017 All rights reserve.</p>
    </div>
    <!-- Main Container End -->
    <script type="text/javascript" src="${pageContext.request.contextPath}/res/js/jquery.min.js"></script>
    <script type="text/javascript" src="${pageContext.request.contextPath}/res/js/bootstrap.min.js"></script>
</body>

</html>

src/main/webapp/WEB-INF/jsp/enterpise/view-apply.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
 <%@ taglib prefix="c"   uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE HTML>
<html lang="zh-CN">

<head>
    <meta charset="UTF-8">
    <title>万才网</title>
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="apple-mobile-web-app-capable" content="no" />
    <meta name="format-detection" content="telephone=no">
    <link rel="stylesheet" type="text/css" href="${pageContext.request.contextPath}/res/css/style-bootstrap.css" />
    <link rel="stylesheet" type="text/css" href="${pageContext.request.contextPath}/res/css/style-enterpise.css" />
    <script type="text/javascript">
    		var id = "${applyEntity.id}";
    </script>
</head>

<body>
    <!-- Navbar Begin -->
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
                    aria-expanded="false">
                    <span class="sr-only">展开导航栏</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">万才网</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="index.html">首页</a>
                    </li>
                    <li class="active">
                        <a href="index.html">招聘管理</a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="logout">退出</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- Navbar end -->
    <!-- Banner Begin -->
    <div class="banner-container">
        <p class="title">招聘管理后台</p>
        <p>HR Control Panel</p>
    </div>
    <!-- Banner End -->
    <!-- Main Container -->
    <div class="container content">
        <div class="col-md-3">
            <div class="list-group">
                <div class="list-group-item header"> 菜单 Menu</div>
                <a href="mgr-jobs.html" class="list-group-item">招聘职位管理</a>
                <a href="mgr-apply.html" class="list-group-item">简历投递管理</a>
            </div>
        </div>
        <div class="col-md-9">
            <div class="list-group row">
                <div class="list-group-item text-left header">申请职位 Apply Job</div>
                <div class="list-group-item text-left">
                    <p>${applyEntity.job.jobName }</p>
                </div>
            </div>
            <div class="list-group row">
                <div class="list-group-item text-left header">基本信息 Infomation</div>
                <div class="list-group-item text-left">
                    <p>姓名：${applyEntity.resume.name }</p>
                    <p>性别：${applyEntity.resume.gender }</p>
                    <p>出生年月：${applyEntity.resume.birthday }</p>
                    <p>参加工作室时间：${applyEntity.resume.timeToWork }</p>
                    <p>现在居住的城市：${applyEntity.resume.residence }</p>
                    <p>户口所在地：${applyEntity.resume.originResidence }</p>
                    <p>手机号码：${applyEntity.resume.phone }</p>
                    <p>电子邮箱：${applyEntity.resume.email }</p>
                </div>
            </div>
            <div class="list-group row">
                <div class="list-group-item text-left header">教育信息 Education Information</div>
                <c:forEach items="${requestScope.applyEntity.resume.educationDeatil }" var="item">
                <div class="list-group-item education">
                    <p>学校名称：${item.schoolName }</p>
                    <p>入学时间：${item.enrollmentTime }</p>
                    <p>毕业时间：${item.graduateTime }</p>
                    <p>专业：${item.major }</p>
                    <p>学位学历：${item.degree }</p>
                </div>
                </c:forEach>
                
            </div>
            <div class="list-group row">
                <div class="list-group-item text-left header">工作经历 Work Experience</div>
                 <c:forEach items="${requestScope.applyEntity.resume.experienceDetail }" var="item">
                <div class="list-group-item experience">
                    <p>公司名称：${item.companyName }</p>
                    <p>开始时间：${item.beginTime }</p>
                    <p>结束时间：${item.endTime }</p>
                    <p>所在行业：${item.industry }</p>
                    <p>工作描述：${item.describe }</p>
                </div>
                </c:forEach>
            </div>
            <div class="list-group row">
                <div class="list-group-item text-left header">项目经验 Project Experience</div>
                <div class="list-group-item text-left">
                    <p>${applyEntity.resume.projectExperience }</p>
                </div>
            </div>
            <div class="list-group row">
                <div class="list-group-item text-left header">自我评价 Self-Appraisal</div>
                <div class="list-group-item text-left">
                    <p>${applyEntity.resume.evaluate }</p>
                </div>
            </div>
            <div class="list-group row">
                <div class="list-group-item text-left header">操作 Operation</div>
                <div class="list-group-item text-center">
                <c:if test="${!applyEntity.handle }">
                	   <button class="btn btn-info" id="acceptBtn" type="button">通过简历，允许面试</button> 
                    <button class="btn btn-danger" id="refuseBtn" type="button">拒绝简历</button>
                </c:if>
                <c:if test="${applyEntity.handle }">
                	   <p>您已经处理了本简历</p>
                </c:if>
                </div>
            </div>
        </div>
    </div>
    <div class="footer">
        <p>
            <a href="enterprise-login.html">我要发布招聘信息</a>
        </p>
        <p>Guangzhou College &copy; 2006-2017 All rights reserve.</p>
    </div>
    <!-- Main Container End -->
    <script type="text/javascript" src="${pageContext.request.contextPath}/res/js/jquery.min.js"></script>
    <script type="text/javascript" src="${pageContext.request.contextPath}/res/js/bootstrap.min.js"></script>
     <c:if test="${!applyEntity.handle }">
     <script type="text/javascript" src="${pageContext.request.contextPath}/res/js/handle-apply.js"></script>    
     </c:if>
</body>

</html>